name: Rebase on Upstream

on:
  schedule:
  - cron: "15 11 * * *"  
  workflow_dispatch:    # run manually

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: yt-dlp/rebase-upstream-action@master
    - uses: actions/checkout@master
  rebase2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: no-gpu
        fetch-depth: 0
    - uses: yt-dlp/rebase-upstream-action@master
    - uses: actions/checkout@master    
        persist-credentials: false
    - uses: yt-dlp/rebase-upstream-action@master
